### PR TITLE
Handle symbol keys for dotted paths

### PR DESCRIPTION
**Pull request by capoferro**
Ran into an issue with mb where attributes are passed in as symbols to be broken down. Chozo's dotted_paths returns nil when a symbol is passed in, so mb explodes.

### CODE REVIEW

**Comment by reset** [comment]
@bluepojo good find but I think it's best to standardize on returning a hash of strings even if we are given a symbol value for the dotted path. I created #19 and used your test to show this functionality.

What do you think?

**Comment by capoferro** [comment]
My thought was that returning what you're given is more intuitive.  If you want strings back, pass a string. If you want symbols, pass a symbol. It could be mb would prefer strings, but in that case mb should call #to_s on the key. I don't think Hash should make that decision for you as it's a generic utility.

Are there other examples where Hash (or a similar std lib data structure) changes type from what is passed in?

**Comment by reset** [comment]
@bluepojo I'm not aware of any STL functions on Hash that change the structure of the Hash based on the type of value passed in as a parameter.

I think it's a bit intrusive to change the contents of the Hash based on the type of value passed in as a parameter. If you really want that Hash to have symbols for keys there's the #deep_symbolize_keys function.

**Comment by capoferro** [comment]
This doesn't change the contents of the hash. This says "if you pass me a symbol key to break up into subhashes, I will keep your keys as symbols rather than converting your keys to strings."

I suppose I'm confused why maintaining the type passed in is more intrusive than converting the type.

**Comment by justincampbell** [comment]
@bluepojo My gut agrees with @reset, but I don't mind it because it doesn't change the behavior of a string passed in.

Also I'd like to point out, you'd probably be using this with a variable, not typing the symbol in code. So it would look like `Hash.from_dotted_path(path.to_sym, value)`, which makes more sense in my head than the `:'a.b.c'` example.

**Comment by reset** [comment]
@bluepojo @justincampbell I don't think it's intuitive to base the return value of `from_dotted_path` on the type of the 'dotted path' parameter.

I didn't mean it would _change_ the contents of the Hash because the Hash doesn't exist yet; what I mean is it would _change_ the contents of what you expect to receive back.

You can just chain a deep_symbolize_keys function to the return value of this and you'll get what you want. We could also have this function take an options hash and include an option like `:symbolize_keys` which ensure that the Hash we receive back is a Hash of symbolized keys.

**Comment by capoferro** [comment]
The way it works in my head:

I give you a trout to chop up into pieces. You give me back pieces of trout.
I give you a tuna to chop up into pieces. You give me back pieces of tuna.

I give you a symbol to chop up into pieces. You give me back pieces of symbol.
I give you a string to chop up into pieces. You give me back pieces of string.

It doesn't make sense to give back pieces of tuna when you're passed a trout to chop up, imo.

**Comment by reset** [comment]
@bluepojo the parameter given is a notation for a nested Hash to create. It's not being converted into Hash like the first in your analogy.

I think the appropriate approach for this is to have an option which will allow you to explicitly request modifications to the way the Hash looks that is returned to you.

``` ruby
Hash.from_dotted_path('one.two.three', symbolize_keys: true)
```

versus

``` ruby
Hash.from_dotted_path(:'one.two.three')
```

**Comment by capoferro** [comment]
I still don't agree that your way makes logical sense, but I don't really care that much. It works well enough your way, even if it's less intuitive.

**Comment by reset** [comment]
I think the argument of intuitiveness would be a lot easier to swallow if we could pinpoint one or two generators/factories in STL, or a widely used library, which dynamically changes the object returned/generated based on the _type_ of the parameters

**Comment by capoferro** [comment]
Converting the Symbol key to Strings qualifies as dynamically changing the object, imo. Keeping the keys as symbols is an attempt _not_ to change the object.

Keep the object type the same as the input and _don't_ change it.

I asked a good number of people on IRC in several channels which they think is more intuitive, and the vast majority preferred "Symbol in, Symbols out." (that is: all but 1, and that 1 waffled a bit) If you want to do your own thing, so be it, just realize most people think that converting the Symbol key passed in to Strings is not more intuitive.

Gonna leave this be now, since you've decided. :+1:

**Pull request closed without merging**
